name: phonebook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  http: ^0.13.4
  intl: ^0.17.0
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
  drift_dev: ^1.0.2
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
